#!/bin/bash

#################### Script Header #########################
#Script Name    : create_usb_iso
#Description    : usage: create_usb_iso image usb-path                             
#                 i.e.:
#                     create_usb_iso /tmp/builds/cbirnos.iso /dev/ttyUSB0
#Author         : Anil Sharma (CBIR 2013 - 2015)
#Email          : cbir.anil@gmail.com
#################### End #################################

set -e
set -o pipefail

MINPARAMS=2
if [ $# -lt "$MINPARAMS" ]
then
    echo usage:
    echo   create_usb_iso "image" "usb-path"
    echo
    echo i.e.:
    echo   create_usb_iso /tmp/builds/cbirnos.iso /dev/ttyUSB0
    echo
    exit 1
fi

isohybrid $1
dd if=$1  of=$2

