#!/bin/bash

#################### Script Header #########################
#Author         : Anil Sharma (CBIR 2013 - 2015)
#Email          : cbir.anil@gmail.com
#################### End #################################
# Place yourself outside of the OpenSSL source tree.  In
# this example, the environment variable OPENSSL_SOURCE
# is assumed to contain the absolute OpenSSL source directory.

(cd $OPENSSL_SOURCE; find . -type f) | while read F; do
	mkdir -p `dirname $F`
	ln -s $OPENSSL_SOURCE/$F $F
done

